(setq package-enable-at-startup nil)
(setq native-comp-deferred-compilation nil)
(push '(menu-bar-lines . 0) default-frame-alist)
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(vertical-scroll-bars) default-frame-alist)

;; set path, MacOS does not export path to gui apps
(add-to-list 'exec-path "/opt/homebrew/bin")
(add-to-list 'exec-path "/Users/jlima/.virtualenvs/prod3/bin")
(add-to-list 'exec-path "/Users/jlima/.nvm/versions/node/v23.5.0/bin")
(add-to-list 'exec-path "/Users/jlima/.fzf/bin")
(add-to-list 'exec-path "/Users/jlima/.local/bin")
(add-to-list 'exec-path "/Users/jlima/.deno/bin")
(add-to-list 'exec-path "/Users/jlima/local/bin")
(add-to-list 'exec-path "/opt/homebrew/sbin")
(add-to-list 'exec-path "/usr/local/sbin")
(add-to-list 'exec-path "/snap/bin")
(add-to-list 'exec-path "/opt/homebrew/opt/grep/libexec/gnubin")
(add-to-list 'exec-path "/opt/homebrew/opt/gnu-sed/libexec/gnubin")
(add-to-list 'exec-path "/Users/jlima/go/bin")
(add-to-list 'exec-path "/Users/jlima/.rd/bin")
(add-to-list 'exec-path "/Users/jlima/.luarocks/bin")
(add-to-list 'exec-path "/opt/homebrew/bin")
(add-to-list 'exec-path "/Users/jlima/.npm-packages/bin")
(add-to-list 'exec-path "/Users/jlima/local/node/bin")
(add-to-list 'exec-path "/Users/jlima/local/yarn/bin")
(add-to-list 'exec-path "/Users/jlima/bin")
(add-to-list 'exec-path "/usr/local/bin")
(add-to-list 'exec-path "/usr/local/share/dotnet")
(add-to-list 'exec-path "/usr/lib/cargo/bin")
(add-to-list 'exec-path "/Users/jlima/.cargo/bin")
(add-to-list 'exec-path "/System/Cryptexes/App/usr/bin")
(add-to-list 'exec-path "/usr/bin")
(add-to-list 'exec-path "/bin")
(add-to-list 'exec-path "/usr/sbin")
(add-to-list 'exec-path "/sbin")
(add-to-list 'exec-path "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin")
(add-to-list 'exec-path "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin")
(add-to-list 'exec-path "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin")
(add-to-list 'exec-path "/Library/Apple/usr/bin")

